import { useState, useRef, useEffect, type KeyboardEvent } from 'react';
import { Link } from 'react-router-dom';
import { Download, Loader2, RotateCw, ImageIcon } from 'lucide-react';
import { useSEO } from '../hooks/useSEO';
import { chat } from '../lib/providers';

type Status = 'idle' | 'loading' | 'done' | 'error';

// Shown instantly on load and kept as a fallback if the AI-generated set
// below fails - the chips should never be empty while waiting on a network call.
const FALLBACK_EXAMPLES = [
  'a minimalist poster for an AI engineering blog, deep green and black',
  'an isometric illustration of a neural network as a small city',
  'a retro terminal glowing in a dark room, cinematic',
  'a hummingbird made of circuit traces, on white',
];

const EXAMPLES_SYSTEM_PROMPT = `You generate creative image-prompt ideas for an AI image generator playground on a software engineer's portfolio site. Return EXACTLY 4 short prompt ideas, one per line, no numbering, no quotes, no extra commentary. Each must be a vivid, concrete visual description under 70 characters, lowercase. Match this exact style:
a minimalist poster for an AI engineering blog, deep green and black
a retro terminal glowing in a dark room, cinematic
Mix themes across the 4: engineering/tech, nature or animals, abstract/artistic, sci-fi or retro. Be genuinely different each time - avoid defaulting to "robot" or "circuit board" every time.`;

function parseExamples(raw: string): string[] {
  const lines = raw
    .split('\n')
    .map(l => l.replace(/^[\s"'\-\d.)]+/, '').replace(/["']+$/, '').trim())
    .filter(l => l.length > 8 && l.length < 100);
  return lines.slice(0, 4);
}

export default function ImaginePage() {
  const [prompt, setPrompt] = useState('');
  const [submitted, setSubmitted] = useState('');
  const [src, setSrc] = useState('');
  const [status, setStatus] = useState<Status>('idle');
  const [source, setSource] = useState('');
  const [examples, setExamples] = useState<string[]>(FALLBACK_EXAMPLES);
  const srcRef = useRef('');

  useSEO({
    title: 'Imagine',
    description: 'Generate images from a text prompt. Free, in-browser, no sign-up.',
    noindex: true,
  });

  // Fresh prompt ideas every visit, generated by the model instead of the
  // same 4 static chips forever. Falls back to FALLBACK_EXAMPLES on error.
  useEffect(() => {
    let cancelled = false;
    chat({
      // 'chat' leads with Groq (near-instant, no hidden reasoning phase) -
      // 'fast' leads with HuggingFace, which took 5-6s here, too slow for
      // chips that are supposed to feel instant.
      tier: 'chat',
      maxTokens: 150,
      temperature: 1.05,
      messages: [
        { role: 'system', content: EXAMPLES_SYSTEM_PROMPT },
        { role: 'user', content: 'Give me 4 prompt ideas.' },
      ],
    })
      .then(raw => {
        if (cancelled) return;
        const parsed = parseExamples(raw);
        if (parsed.length === 4) setExamples(parsed);
      })
      .catch(() => {
        // Keep the static fallback already showing
      });
    return () => { cancelled = true; };
  }, []);

  async function generate(p: string) {
    const text = p.trim();
    if (!text || status === 'loading') return;
    setSubmitted(text);
    setStatus('loading');
    try {
      const res = await fetch('/api/image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: text }),
      });
      if (!res.ok) throw new Error('generation failed');
      const blob = await res.blob();
      setSource(res.headers.get('X-Image-Source') ?? '');
      const url = URL.createObjectURL(blob);
      if (srcRef.current) URL.revokeObjectURL(srcRef.current);
      srcRef.current = url;
      setSrc(url);
      setStatus('done');
    } catch {
      setStatus('error');
    }
  }

  const onKey = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') generate(prompt);
  };

  return (
    <main style={{ minHeight: '100vh', paddingTop: '110px', paddingBottom: '80px' }}>
      <div style={{ maxWidth: '780px', margin: '0 auto', padding: '0 clamp(16px, 5vw, 24px)' }}>
        {/* Header */}
        <div className="page-breadcrumb" style={{
          fontFamily: "'JetBrains Mono', monospace",
          fontSize: '0.8rem',
          color: 'var(--text-dim)',
          letterSpacing: '0.05em',
          marginBottom: '24px',
          display: 'flex', alignItems: 'center', gap: '6px',
        }}>
          <Link to="/" style={{ color: 'var(--accent)', textDecoration: 'none' }}>~/dhruv</Link>
          <span>/</span>
          <span>imagine</span>
        </div>
        <h1 className="font-display" style={{
          fontSize: 'clamp(1.6rem, 4vw, 2.4rem)', fontWeight: 700, marginBottom: '6px',
        }}>
          Imagine<span style={{ color: 'var(--accent)' }}>.</span>
        </h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '28px' }}>
          Type anything. It generates an image in the browser, free, no sign-up.
        </p>

        {/* Prompt box */}
        <div style={{
          display: 'flex', alignItems: 'center', gap: '10px',
          background: 'var(--surface)', border: '1px solid var(--border-2)',
          borderRadius: '10px', padding: '6px 6px 6px 16px', boxShadow: 'var(--shadow-md)',
        }}>
          <ImageIcon size={16} style={{ color: 'var(--text-dim)', flexShrink: 0 }} />
          <input
            className="search-input"
            value={prompt}
            onChange={e => setPrompt(e.target.value)}
            onKeyDown={onKey}
            placeholder="describe the image you want..."
            disabled={status === 'loading'}
            style={{
              flex: 1, background: 'none', border: 'none', outline: 'none',
              color: 'var(--text)', fontFamily: "'JetBrains Mono', monospace",
              fontSize: '0.88rem', padding: '10px 0', minWidth: 0,
            }}
          />
          <button
            onClick={() => generate(prompt)}
            disabled={status === 'loading' || !prompt.trim()}
            style={{
              display: 'flex', alignItems: 'center', gap: '7px',
              background: status === 'loading' || !prompt.trim() ? 'var(--surface-2)' : 'var(--accent)',
              color: status === 'loading' || !prompt.trim() ? 'var(--text-dim)' : 'var(--chat-user-text)',
              border: 'none', borderRadius: '7px', padding: '10px 16px',
              fontFamily: "'JetBrains Mono', monospace", fontSize: '0.78rem', fontWeight: 600,
              cursor: status === 'loading' || !prompt.trim() ? 'default' : 'pointer',
              transition: 'all 0.18s ease', flexShrink: 0,
            }}
          >
            {status === 'loading' && <Loader2 size={13} className="spin-slow" />}
            {status === 'loading' ? 'generating' : 'generate'}
          </button>
        </div>

        {/* Example chips (idle only) */}
        {status === 'idle' && (
          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginTop: '16px' }}>
            {examples.map(s => (
              <button key={s} onClick={() => { setPrompt(s); generate(s); }} className="search-chip">
                {s.length > 42 ? s.slice(0, 42) + '…' : s}
              </button>
            ))}
          </div>
        )}

        {/* Result */}
        {status !== 'idle' && (
          <div style={{
            marginTop: '22px', background: 'var(--surface)', border: '1px solid var(--border)',
            borderRadius: '14px', overflow: 'hidden', boxShadow: 'var(--shadow-md)',
          }}>
            <div style={{
              width: '100%', aspectRatio: '1', display: 'flex', alignItems: 'center',
              justifyContent: 'center', background: 'var(--surface-2)', position: 'relative',
            }}>
              {status === 'loading' && (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '12px', color: 'var(--text-dim)' }}>
                  <Loader2 size={26} className="spin-slow" style={{ color: 'var(--accent)' }} />
                  <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: '0.72rem' }}>
                    painting your prompt...
                  </span>
                </div>
              )}
              {status === 'error' && (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px', color: 'var(--text-dim)', padding: '24px', textAlign: 'center' }}>
                  <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: '0.75rem' }}>
                    generation failed. the model may be warming up, try again.
                  </span>
                  <button onClick={() => generate(submitted)} className="search-chip" style={{ display: 'inline-flex', alignItems: 'center', gap: '5px' }}>
                    <RotateCw size={11} /> retry
                  </button>
                </div>
              )}
              {status === 'done' && src && (
                <img src={src} alt={submitted} style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
              )}
            </div>

            {status === 'done' && (
              <div style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                gap: '12px', flexWrap: 'wrap', padding: '12px 16px',
                borderTop: '1px solid var(--border)',
              }}>
                <span style={{
                  fontFamily: "'JetBrains Mono', monospace", fontSize: '0.66rem',
                  color: 'var(--text-dim)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                  maxWidth: '55%',
                }}>
                  {source === 'hf-flux' ? 'FLUX' : source === 'pollinations' ? 'Pollinations' : 'generated'} · {submitted}
                </span>
                <div style={{ display: 'flex', gap: '6px' }}>
                  <button onClick={() => generate(submitted)} className="search-chip" style={{ display: 'inline-flex', alignItems: 'center', gap: '5px' }}>
                    <RotateCw size={11} /> regenerate
                  </button>
                  <a href={src} download="imagine.png" className="search-chip" style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', textDecoration: 'none' }}>
                    <Download size={11} /> download
                  </a>
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      <style>{`
        @keyframes spin-slow-kf { to { transform: rotate(360deg); } }
        .spin-slow { animation: spin-slow-kf 1s linear infinite; }
        .search-chip {
          padding: 6px 12px; border-radius: 6px;
          border: 1px solid var(--border); background: transparent;
          color: var(--text-dim); font-family: 'JetBrains Mono', monospace;
          font-size: 0.7rem; cursor: pointer; transition: all 0.18s ease;
        }
        .search-chip:hover { border-color: var(--accent); color: var(--accent); }
        @media (max-width: 640px) {
          .search-input { font-size: 16px !important; }
        }
      `}</style>
    </main>
  );
}
