// One-off seed list transcribed from local library folders, for the bulk
// import button in the admin Movies tab. All are films already WATCHED, with
// no rating or review - those get added later, by hand, per film.
//
// Deliberately NOT auto-generating reviews: a made-up opinion attributed to
// you is worse than an empty field.
//
// Excluded during transcription: TV/anime series (Chernobyl, Twin Peaks, The
// Patient, The Bear, Crash Landing on You, Modern Love, Love in Contract,
// Panchayat, Cult of Fear, Angry Young Men, Space Brothers, Attack on Titan,
// Kanojo Okarishimasu), phone videos (VID_*.mp4), subtitle files and folders.
//
// Duplicates already collapsed here (each appeared twice across folders):
// Grosse Pointe Blank, Oye Lucky! Lucky Oye!, Only Yesterday, Soul,
// Sleepless in Seattle, Funny Games. The import is also idempotent server-side
// (it upserts on tmdb_id / title), so re-running it will not create doubles.
export const MOVIE_SEED = [
  { title: '2001: A Space Odyssey', year: 1968 },
  { title: 'Apollo 10½: A Space Age Childhood', year: 2022 },
  { title: 'Butch Cassidy and the Sundance Kid', year: 1969 },
  { title: 'Grosse Pointe Blank', year: 1997 },
  { title: 'Mr. & Mrs. Smith', year: 2005 },
  { title: 'Only Yesterday', year: 1991 },
  { title: 'Oye Lucky! Lucky Oye!', year: 2008 },
  { title: 'The Good, the Bad and the Ugly', year: 1966 },
  { title: 'Mean Streets', year: 1973 },
  { title: 'Midnight Cowboy', year: 1969 },
  { title: 'Stalker', year: 1979 },
  { title: 'Days of Heaven', year: 1978 },
  { title: 'Wings of Desire', year: 1987 },
  { title: 'Bicycle Thieves', year: 1948 },

  { title: 'Roman Holiday', year: 1953 },
  { title: 'The Last Samurai', year: 2003 },
  { title: 'The Handmaiden', year: 2016 },
  { title: 'Vadh', year: 2022 },
  { title: 'Aamis', year: 2019 },
  { title: 'All India Rank', year: 2024 },
  { title: 'Chup: Revenge of the Artist', year: 2022 },
  { title: 'Dead Poets Society', year: 1989 },
  { title: 'Delhi Belly', year: 2011 },
  { title: 'Fallen Leaves', year: 2023 },
  { title: 'Funny Games', year: 1997 },
  { title: 'Karthik Calling Karthik', year: 2010 },
  { title: 'Kill Bill: Vol. 1', year: 2003 },
  { title: 'Kill Bill: Vol. 2', year: 2004 },
  { title: 'Killa', year: 2014 },
  { title: 'Perfect Days', year: 2023 },
  { title: 'Princess Mononoke', year: 1997 },
  { title: 'Raman Raghav 2.0', year: 2016 },
  { title: 'Scent of a Woman', year: 1992 },
  { title: 'Soul', year: 2020 },
  { title: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001 },
  { title: 'The Lord of the Rings: The Two Towers', year: 2002 },
  { title: 'The Lord of the Rings: The Return of the King', year: 2003 },
  { title: 'The Other Boleyn Girl', year: 2008 },
  { title: 'There Will Be Blood', year: 2007 },
  { title: 'Wind River', year: 2017 },

  { title: 'Breathe', year: 2017 },
  { title: 'Lost Highway', year: 1997 },
  { title: "Schindler's List", year: 1993 },
  { title: 'The Worst Person in the World', year: 2021 },
  { title: 'Young Frankenstein', year: 1974 },

  { title: 'Moonlight', year: 2016 },
  { title: "America's Sweethearts", year: 2001 },
  { title: 'Annie Hall', year: 1977 },
  { title: 'Barry Lyndon', year: 1975 },
  { title: 'Binny and Family', year: 2024 },
  { title: 'Drawing Closer', year: 2024 },
  { title: 'Eraserhead', year: 1977 },
  { title: 'EuroTrip', year: 2004 },
  { title: 'How to Make Millions Before Grandma Dies', year: 2024 },
  { title: 'Jujutsu Kaisen 0', year: 2021 },
  { title: 'Love Story', year: 1970 },
  { title: 'No Other Choice', year: 2025 },
  { title: 'Pieces of a Woman', year: 2020 },
  { title: 'Prisoners', year: 2013 },
  { title: 'Psycho', year: 1960 },
  { title: 'Rental Family', year: 2025 },
  { title: 'Reservoir Dogs', year: 1992 },
  { title: 'A Silent Voice', year: 2016 },
  { title: 'Sister Midnight', year: 2024 },
  { title: 'The Little Prince', year: 2015 },
  { title: 'The Pale Blue Eye', year: 2022 },
  { title: 'The Shawshank Redemption', year: 1994 },
  { title: 'U Turn', year: 1997 },
  { title: 'When Harry Met Sally...', year: 1989 },

  { title: 'Awakenings', year: 1990 },
  { title: 'Cast Away', year: 2000 },
  { title: 'In Bruges', year: 2008 },
  { title: 'Mrs. Doubtfire', year: 1993 },
  { title: 'O Brother, Where Art Thou?', year: 2000 },
  { title: 'October Sky', year: 1999 },
  { title: 'Spy x Family Code: White', year: 2023 },
  { title: 'The Bucket List', year: 2007 },

  { title: 'Sir', year: 2018 },
  { title: 'American Beauty', year: 1999 },
  { title: 'Brahman Naman', year: 2016 },
  { title: 'Chopsticks', year: 2019 },
  { title: 'Chungking Express', year: 1994 },
  { title: 'Crash', year: 2004 },
  { title: 'Detachment', year: 2011 },
  { title: 'Fandry', year: 2013 },
  { title: 'In the Mood for Love', year: 2000 },
  { title: 'Jojo Rabbit', year: 2019 },
  { title: 'Love Sex Aur Dhokha', year: 2010 },
  { title: 'Lucky Baskhar', year: 2024 },
  { title: 'Memories of Murder', year: 2003 },
  { title: 'Modest Heroes', year: 2018 },
  { title: 'Mulholland Drive', year: 2001 },
  { title: 'Not Another Teen Movie', year: 2001 },
  { title: 'Oldboy', year: 2003 },
  { title: 'Paris, Texas', year: 1984 },
  { title: 'Sairat', year: 2016 },
  { title: 'Shanghai', year: 2012 },
  { title: 'Sita Ramam', year: 2022 },
  { title: 'The Disciple', year: 2020 },
  { title: 'The Breadwinner', year: 2017 },
  { title: 'The Holdovers', year: 2023 },
  { title: 'The Menu', year: 2022 },
  { title: 'The Social Network', year: 2010 },
  { title: 'Three of Us', year: 2022 },
  { title: 'Zodiac', year: 2007 },

  { title: 'Newton', year: 2017 },

  { title: 'Boogie Nights', year: 1997 },
  { title: 'City Lights', year: 1931 },
  { title: 'Gone Girl', year: 2014 },
  { title: 'Little Miss Sunshine', year: 2006 },
  { title: 'Paddington', year: 2014 },
  { title: 'RED', year: 2010 },
  { title: 'Ship of Theseus', year: 2012 },
  { title: 'The French Dispatch', year: 2021 },
  { title: 'The Princess Bride', year: 1987 },
  { title: 'School of Rock', year: 2003 },
  { title: 'The Usual Suspects', year: 1995 },
  { title: 'Then Came You', year: 2018 },

  { title: 'Django Unchained', year: 2012 },
  { title: 'Hugo', year: 2011 },
  { title: 'Sleepless in Seattle', year: 1993 },
  { title: 'To Kill a Mockingbird', year: 1962 },
  { title: 'What Women Want', year: 2000 },
  { title: 'While You Were Sleeping', year: 1995 },

  { title: 'Manchester by the Sea', year: 2016 },
  { title: 'Ankhon Dekhi', year: 2014 },
  { title: 'Spree', year: 2020 },
  { title: 'Suraj Ka Satvan Ghoda', year: 1992 },
  { title: 'The Texas Chain Saw Massacre', year: 1974 },
  { title: 'Titli', year: 2014 },
  { title: 'Ugly', year: 2013 },
];
